// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.573
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------


/// <remarks/>
[System.Web.Services.WebServiceBinding(Name="POBoxServiceSoap",Namespace="http://novell.com/simias/pobox/"),
System.Diagnostics.DebuggerStepThroughAttribute(),
System.ComponentModel.DesignerCategoryAttribute("code")]
public class POBoxService: System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    public POBoxService () {
        this.Url = "http://localhost/simias10/POService.asmx";
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/pobox/Ping",RequestNamespace="http://novell.com/simias/pobox/",ResponseNamespace="http://novell.com/simias/pobox/",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public int Ping(int sleepFor) {
        object[] results = this.Invoke("Ping", new object[] {
            sleepFor});
        return ((int)(results[0]));
    }
    
    public System.IAsyncResult BeginPing(int sleepFor, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Ping", new object[] {
            sleepFor}, callback, asyncState);
    }
    
    public int EndPing(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/pobox/AcceptedSubscription",RequestNamespace="http://novell.com/simias/pobox/",ResponseNamespace="http://novell.com/simias/pobox/",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public POBoxStatus AcceptedSubscription(SubscriptionMsg subMsg) {
        object[] results = this.Invoke("AcceptedSubscription", new object[] {
            subMsg});
        return ((POBoxStatus)(results[0]));
    }
    
    public System.IAsyncResult BeginAcceptedSubscription(SubscriptionMsg subMsg, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AcceptedSubscription", new object[] {
            subMsg}, callback, asyncState);
    }
    
    public POBoxStatus EndAcceptedSubscription(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((POBoxStatus)(results[0]));
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/pobox/DeclinedSubscription",RequestNamespace="http://novell.com/simias/pobox/",ResponseNamespace="http://novell.com/simias/pobox/",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public POBoxStatus DeclinedSubscription(SubscriptionMsg subMsg) {
        object[] results = this.Invoke("DeclinedSubscription", new object[] {
            subMsg});
        return ((POBoxStatus)(results[0]));
    }
    
    public System.IAsyncResult BeginDeclinedSubscription(SubscriptionMsg subMsg, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeclinedSubscription", new object[] {
            subMsg}, callback, asyncState);
    }
    
    public POBoxStatus EndDeclinedSubscription(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((POBoxStatus)(results[0]));
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/pobox/AckSubscription",RequestNamespace="http://novell.com/simias/pobox/",ResponseNamespace="http://novell.com/simias/pobox/",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public POBoxStatus AckSubscription(SubscriptionMsg subMsg) {
        object[] results = this.Invoke("AckSubscription", new object[] {
            subMsg});
        return ((POBoxStatus)(results[0]));
    }
    
    public System.IAsyncResult BeginAckSubscription(SubscriptionMsg subMsg, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AckSubscription", new object[] {
            subMsg}, callback, asyncState);
    }
    
    public POBoxStatus EndAckSubscription(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((POBoxStatus)(results[0]));
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/pobox/GetSubscriptionInfo",RequestNamespace="http://novell.com/simias/pobox/",ResponseNamespace="http://novell.com/simias/pobox/",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public SubscriptionInformation GetSubscriptionInfo(string domainID, string identityID, string subscriptionID, string collectionID) {
        object[] results = this.Invoke("GetSubscriptionInfo", new object[] {
            domainID,
            identityID,
            subscriptionID,
            collectionID});
        return ((SubscriptionInformation)(results[0]));
    }
    
    public System.IAsyncResult BeginGetSubscriptionInfo(string domainID, string identityID, string subscriptionID, string collectionID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetSubscriptionInfo", new object[] {
            domainID,
            identityID,
            subscriptionID,
            collectionID}, callback, asyncState);
    }
    
    public SubscriptionInformation EndGetSubscriptionInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SubscriptionInformation)(results[0]));
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/pobox/SaveSubscription",RequestNamespace="http://novell.com/simias/pobox/",ResponseNamespace="http://novell.com/simias/pobox/",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public POBoxStatus SaveSubscription(string subscription) {
        object[] results = this.Invoke("SaveSubscription", new object[] {
            subscription});
        return ((POBoxStatus)(results[0]));
    }
    
    public System.IAsyncResult BeginSaveSubscription(string subscription, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveSubscription", new object[] {
            subscription}, callback, asyncState);
    }
    
    public POBoxStatus EndSaveSubscription(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((POBoxStatus)(results[0]));
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/pobox/RemoveCollectionBySubscription",RequestNamespace="http://novell.com/simias/pobox/",ResponseNamespace="http://novell.com/simias/pobox/",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public void RemoveCollectionBySubscription(string subscription) {
        this.Invoke("RemoveCollectionBySubscription", new object[] {
            subscription});
    }
    
    public System.IAsyncResult BeginRemoveCollectionBySubscription(string subscription, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RemoveCollectionBySubscription", new object[] {
            subscription}, callback, asyncState);
    }
    
    public void EndRemoveCollectionBySubscription(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/pobox/RemoveSubscriptionsForCollection",RequestNamespace="http://novell.com/simias/pobox/",ResponseNamespace="http://novell.com/simias/pobox/",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public void RemoveSubscriptionsForCollection(string domainID, string collectionID) {
        this.Invoke("RemoveSubscriptionsForCollection", new object[] {
            domainID,
            collectionID});
    }
    
    public System.IAsyncResult BeginRemoveSubscriptionsForCollection(string domainID, string collectionID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RemoveSubscriptionsForCollection", new object[] {
            domainID,
            collectionID}, callback, asyncState);
    }
    
    public void EndRemoveSubscriptionsForCollection(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/pobox/RemoveSubscriptionByMember",RequestNamespace="http://novell.com/simias/pobox/",ResponseNamespace="http://novell.com/simias/pobox/",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public void RemoveSubscriptionByMember(string domainID, string collectionID, string userID) {
        this.Invoke("RemoveSubscriptionByMember", new object[] {
            domainID,
            collectionID,
            userID});
    }
    
    public System.IAsyncResult BeginRemoveSubscriptionByMember(string domainID, string collectionID, string userID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RemoveSubscriptionByMember", new object[] {
            domainID,
            collectionID,
            userID}, callback, asyncState);
    }
    
    public void EndRemoveSubscriptionByMember(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://novell.com/simias/pobox/Invite",RequestNamespace="http://novell.com/simias/pobox/",ResponseNamespace="http://novell.com/simias/pobox/",ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped,Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public POBoxStatus Invite(SubscriptionMsg subMsg) {
        object[] results = this.Invoke("Invite", new object[] {
            subMsg});
        return ((POBoxStatus)(results[0]));
    }
    
    public System.IAsyncResult BeginInvite(SubscriptionMsg subMsg, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Invite", new object[] {
            subMsg}, callback, asyncState);
    }
    
    public POBoxStatus EndInvite(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((POBoxStatus)(results[0]));
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlType(Namespace="http://novell.com/simias/pobox/")]
public class SubscriptionMsg {
    
    /// <remarks/>
    public string DomainID;
    
    /// <remarks/>
    public string FromID;
    
    /// <remarks/>
    public string FromName;
    
    /// <remarks/>
    public string ToID;
    
    /// <remarks/>
    public string SubscriptionID;
    
    /// <remarks/>
    public string SharedCollectionID;
    
    /// <remarks/>
    public string SharedCollectionName;
    
    /// <remarks/>
    public string SharedCollectionType;
    
    /// <remarks/>
    public string DirNodeID;
    
    /// <remarks/>
    public string DirNodeName;
    
    /// <remarks/>
    public int AccessRights;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://novell.com/simias/pobox/")]
public enum POBoxStatus {
    
    /// <remarks/>
    Success,
    
    /// <remarks/>
    UnknownPOBox,
    
    /// <remarks/>
    UnknownIdentity,
    
    /// <remarks/>
    UnknownSubscription,
    
    /// <remarks/>
    UnknownCollection,
    
    /// <remarks/>
    UnknownDomain,
    
    /// <remarks/>
    InvalidState,
    
    /// <remarks/>
    InvalidAccessRights,
    
    /// <remarks/>
    AlreadyAccepted,
    
    /// <remarks/>
    AlreadyDeclined,
    
    /// <remarks/>
    NotPosted,
    
    /// <remarks/>
    UnknownError,
}

/// <remarks/>
[System.Xml.Serialization.XmlType(Namespace="http://novell.com/simias/pobox/")]
public class SubscriptionInformation {
    
    /// <remarks/>
    public string Name;
    
    /// <remarks/>
    public string MsgID;
    
    /// <remarks/>
    public string FromID;
    
    /// <remarks/>
    public string FromName;
    
    /// <remarks/>
    public string ToID;
    
    /// <remarks/>
    public string ToNodeID;
    
    /// <remarks/>
    public string ToName;
    
    /// <remarks/>
    public int AccessRights;
    
    /// <remarks/>
    public string CollectionID;
    
    /// <remarks/>
    public string CollectionName;
    
    /// <remarks/>
    public string CollectionType;
    
    /// <remarks/>
    public string DirNodeID;
    
    /// <remarks/>
    public string DirNodeName;
    
    /// <remarks/>
    public string DomainID;
    
    /// <remarks/>
    public string DomainName;
    
    /// <remarks/>
    public int State;
    
    /// <remarks/>
    public int Disposition;
    
    /// <remarks/>
    public POBoxStatus Status;
}

