#!/bin/sh
#######################################################################
#
#  $RCSfile$
#
#  Copyright (C) 2004 Novell, Inc.
#
#  Author: Rob
#
#######################################################################

export MONO_PATH=/opt/novell/ifolder3/web:$MONO_PATH

if [ "${OSTYPE:0:6}" == "darwin" ]
then
	echo "Increasing ulimit -n to 2048"
	export DYLD_LIBRARY_PATH=/opt/novell/ifolder3/web:/Library/Frameworks/Mono.framework/Versions/Current/lib:$DYLD_LIBRARY_PATH
	ulimit -n 2048
else
	export LD_LIBRARY_PATH=/opt/novell/ifolder3/web:$LD_LIBRARY_PATH
fi

cd /opt/novell/ifolder3/bin
mono /opt/novell/ifolder3/bin/RegisterCmd.exe $@

