<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://novell.com/ifolder/reports/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" targetNamespace="http://novell.com/ifolder/reports/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://novell.com/ifolder/reports/">
      <s:element name="Generate">
        <s:complexType />
      </s:element>
      <s:element name="GenerateResponse">
        <s:complexType />
      </s:element>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="GenerateSoapIn">
    <wsdl:part name="parameters" element="tns:Generate" />
  </wsdl:message>
  <wsdl:message name="GenerateSoapOut">
    <wsdl:part name="parameters" element="tns:GenerateResponse" />
  </wsdl:message>
  <wsdl:portType name="iFolderReportsSoap">
    <wsdl:operation name="Generate">
      <documentation xmlns="http://schemas.xmlsoap.org/wsdl/">Generate the iFolder Reports</documentation>
      <wsdl:input message="tns:GenerateSoapIn" />
      <wsdl:output message="tns:GenerateSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="iFolderReportsSoap" type="tns:iFolderReportsSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
    <wsdl:operation name="Generate">
      <soap:operation soapAction="http://novell.com/ifolder/reports/Generate" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="iFolderReports">
    <documentation xmlns="http://schemas.xmlsoap.org/wsdl/">iFolder Reports Web Service</documentation>
    <wsdl:port name="iFolderReportsSoap" binding="tns:iFolderReportsSoap">
      <soap:address location="http://localhost/simias10/iFolderReports.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>